import { Book } from "./types";

export const dummyBooks: Book[] = [
  {
    id: "1",
    titlePage: "",
    bookName: "Sahih Bukhari Jild 1",
    authorName: "Imam Bukhari",
    subject: "Hadith",
    maktaba: "Maktaba Rehmania",
    libraryCode: "HD-001",
    bookLink: "https://example.com/book1.pdf",
    status: "available",
    // borrowedBy: "Umar",
    addedAt: "2026-07-10",
  },
  {
    id: "2",
    titlePage: "",
    bookName: "Nazm ud Durar Jild 05",
    authorName: "Ibn Kaseer",
    subject: "Tafseer",
    maktaba: "Maktaba Ashrafia",
    bookLink: "https://example.com/book1.pdf",
    libraryCode: "TF-014",
    status: "borrowed",
    borrowedBy: "Bilal Hussain",
    borrowChain: [
      { readerName: "Umar", timestamp: "2026-07-20T10:00:00" },
      { readerName: "Ahmed Raza", timestamp: "2026-07-23T14:00:00" },
      { readerName: "Bilal Hussain", timestamp: "2026-07-26T16:32:00" },
    ],
    addedAt: "2026-07-01",
  },
  {
    id: "3",
    titlePage: "",
    bookName: "Fiqh ul Islam",
    authorName: "Molana Ashraf",
    subject: "Fiqh",
    maktaba: "Maktaba Rehmania",
    libraryCode: "HD-001",
    bookLink: "https://example.com/book1.pdf",
    status: "available",
    addedAt: "2026-06-20",
  },
];
